<a href="https://colab.research.google.com/github/belianp/Cuaderno-de-Algebra/blob/main/CuadernoAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algebra
Cuaderno de algebra

## Matrices


##Definicion
Las matrices son un conjunto bidimensional de números o símbolos distribuidos de forma rectangular, en líneas verticales y horizontales, de manera que sus elementos se organizan en filas y columnas. Sirven para describir sistemas de ecuaciones lineales o diferenciales, así como para representar una aplicación lineal. 

Toda matriz se representa por medio de una letra mayúscula, y sus elementos se reúnen entre dos paréntesis o corchetes, en letra minúscula. A su vez, tienen doble superíndice: el primero hace referencia a la fila y el segundo a la columna a la que pertenece. 

Esta expresión matemática puede sumarse, multiplicarse y descomponerse, por lo que su uso es común en el álgebra lineal.  

##Suma de dos matrices

Usamos + el operador para agregar los elementos correspondientes de dos matrices NumPy.

```python 
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

Output:
[[11  1]
 [ 8  0]]
```

##Multiplicación de dos matrices

Para multiplicar dos matrices, usamos dot() el método. Obtén más información sobre cómo funciona numpy.dot .

Nota: * se utiliza para la multiplicación de matrices (multiplicación de los elementos correspondientes de dos matrices), no para la multiplicación de matrices.

```python 
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

Output:
[[ 36 -12]
 [ -1   2]]
```


##Transposición de una matriz

Usamos numpy.transpose para calcular la transposición de una matriz.

```python 
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

Output:
[[ 1  2  3]
 [ 1  1 -3]]
```

#Acceder a elementos de matriz, filas y columnas.
##Elementos de la matriz 

De manera similar a las listas, podemos acceder a los elementos de la matriz usando index. Comencemos con una matriz NumPy unidimensional.

```python 
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element     
Cuando ejecute el programa, la salida será:

A[0] = 2
A[2] = 6
A[-1] = 10
```

Ahora, veamos cómo podemos acceder a los elementos de un arreglo bidimensional (que es básicamente una matriz).

```python 
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1]) 
```

Cuando ejecutamos el programa, la salida será:

```python 
A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19
```

Filas de acceso de una matriz

```python 
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)
```

Cuando ejecutamos el programa, la salida será:

```python 
A[0] = [1, 4, 5, 12]
A[2] = [-6, 7, 11, 19]
A[-1] = [-6, 7, 11, 19]
```
Acceder a las columnas de una Matriz

```python 
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)
```
Cuando ejecutamos el programa, la salida será:

```python 
A[:,0] = [ 1 -5 -6]
A[:,3] = [12 0 19]
A[:,-1] = [12 0 19]
```


## Python Code
```python 
#Importamos la libreria numpy
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)
```

In [2]:
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)


Coefficients: [ 0.  0. -0.]


# Independencia Lineal 

## Definición
Sea $S = \{\textbf{v}_1, \textbf{v}_2, ...., \textbf{v}_n \}$ un conjunto no vacío de vectores. 

a) Suponga que:

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

implica que $ \alpha_1 = \alpha_2 = ....=\alpha_n$. Se dice entonces que $\textbf{S}$ es ***linealmente independiente***

b) Un conjunto que no es linealmente independiente se llama ***linealmente dependiente***; análogamente,  $\textbf{S}$ es linealmente dependiente si y solo si hay escalares $ \alpha_1 = \alpha_2 = ....=\alpha_n$ **NO** todos cero, tales que

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

## Python Code
```python 
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)
```


In [ ]:
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)



Coefficients: [ 0.  0. -0.]


## Ejercicios