<a href="https://colab.research.google.com/github/belianp/Cuaderno-de-Algebra/blob/main/CuadernoAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algebra
Cuaderno de algebra

## Matrices


##Definicion
Las matrices son un conjunto bidimensional de números o símbolos distribuidos de forma rectangular, en líneas verticales y horizontales, de manera que sus elementos se organizan en filas y columnas. Sirven para describir sistemas de ecuaciones lineales o diferenciales, así como para representar una aplicación lineal. 

Toda matriz se representa por medio de una letra mayúscula, y sus elementos se reúnen entre dos paréntesis o corchetes, en letra minúscula. A su vez, tienen doble superíndice: el primero hace referencia a la fila y el segundo a la columna a la que pertenece. 

Esta expresión matemática puede sumarse, multiplicarse y descomponerse, por lo que su uso es común en el álgebra lineal.  

##Suma de dos matrices

Usamos + el operador para agregar los elementos correspondientes de dos matrices NumPy.

```python 
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

Output:
[[11  1]
 [ 8  0]]
```

##Multiplicación de dos matrices

Para multiplicar dos matrices, usamos dot() el método. Obtén más información sobre cómo funciona numpy.dot .

Nota: * se utiliza para la multiplicación de matrices (multiplicación de los elementos correspondientes de dos matrices), no para la multiplicación de matrices.

```python 
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

Output:
[[ 36 -12]
 [ -1   2]]
```


##Transposición de una matriz

Usamos numpy.transpose para calcular la transposición de una matriz.

```python 
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

Output:
[[ 1  2  3]
 [ 1  1 -3]]
```

#Acceder a elementos de matriz, filas y columnas.
##Elementos de la matriz 

De manera similar a las listas, podemos acceder a los elementos de la matriz usando index. Comencemos con una matriz NumPy unidimensional.

```python 
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element     
Cuando ejecute el programa, la salida será:

A[0] = 2
A[2] = 6
A[-1] = 10
```

Ahora, veamos cómo podemos acceder a los elementos de un arreglo bidimensional (que es básicamente una matriz).

```python 
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1]) 
```

Cuando ejecutamos el programa, la salida será:

```python 
A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19
```

Filas de acceso de una matriz

```python 
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)
```

Cuando ejecutamos el programa, la salida será:

```python 
A[0] = [1, 4, 5, 12]
A[2] = [-6, 7, 11, 19]
A[-1] = [-6, 7, 11, 19]
```
Acceder a las columnas de una Matriz

```python 
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)
```
Cuando ejecutamos el programa, la salida será:

```python 
A[:,0] = [ 1 -5 -6]
A[:,3] = [12 0 19]
A[:,-1] = [12 0 19]
```


# Tipos de Matrices

## Nula
Matriz cuyos elementos son cero

\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}

## Identidad

Si $a_{ij}$ = 0 , $\forall_{ij} \neq j \ \land $ $a_{ij}$ = 1 , $\forall_{ij} = j$

Entonces A se llama I

Ej:

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}

## Matriz Diagonal

$a_{ij}$ = 0 , $\forall_{i} \neq j$
\begin{bmatrix}
0 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 1
\end{bmatrix}

## Matriz Triangulo Superior

Si $a_{ij} = 0, \forall_{i} > j $

Ej:

\begin{bmatrix}
1 & 3 & 2\\
0 & 2 & 4\\
0 & 0 & 1\\
\end{bmatrix}

## Matriz Triangulo Inferior

Si $a_{ij} = 0, \forall_{i} < j$

\begin{bmatrix}
1 & 0 & 0\\
5 & 7 & 0\\
7 & 6 & 2
\end{bmatrix}

## Matriz Simétrica

Si $A = A^T$ entonces $A$ se llama simétrica

Ej:
$A=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end{bmatrix}$


$A^T=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end {bmatrix}$

## Python Code
```python 
#Importamos la libreria numpy
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)
```

In [ ]:
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)


Coefficients: [ 0.  0. -0.]


#Determinante
El determinante de una matriz cuadrada es un número que se obtiene como resultado de realizar una serie de operaciones con sus elementos. De este valor se pueden deducir importantes propiedades de los elementos que lo componen. Tiene, además, muchas aplicaciones en la Geometría y el Álgebra.

Calcular determinantes en Python

Usamos Numpy para calcular los determinantes en Python. Veamos un ejercicio en el que vamos a calcular el determinante de la siguiente matriz A: A = (9)

Como es lógico, el determinante de dicha matriz A de orden 1 va a ser el único valor que contiene dicha matriz.

```python 
#determinantes en Python
import numpy as np

A = np.array ([[9]])
print (A.shape)

print (np.linalg.det (A))
(1, 1)

9.0000000000000002
```
Ese residuo infinitesimal es un redondeo de las operaciones en bytes.

##Propiedades de la función determinante
Las propiedades de los determinantes

Posee dos filas (o columnas) iguales. Todos los elementos de una fila (o una columna) son nulos. Los elementos de una fila (o una columna) son combinación lineal de las otras. 3 Un determinante triangular es igual al producto de los elementos de la diagonal principal.

##Desarrollo del Teorema de Laplace
El teorema afirma que el determinante de una matriz es igual a la suma de los productos de cada elemento (de un renglón o columna) por la determinante de su matriz adjunta, lo que reduce un determinante de dimensión n a n determinantes de dimensión n-1.

##Cálculo de determinantes por el método de Sarrus
La regla de Sarrus es un método que te permite calcular el determinante de una matriz de orden 3 más fácilmente. En este método, las primeras columnas de la matriz se repiten al final y se realiza una multiplicación de diagonales para obtener el determinante.

#Aplicación de determinantes para cálculo del rango de una matriz

##Rango de una matriz
 

El rango de una matriz es el número de filas (o columnas) linealmente independientes. Utilizando esta definición se puede calcular usando el método de Gauss.

También, podemos decir que el rango de una matriz es el orden de la mayor submatriz cuadrada no nula. Utilizando esta definición se puede calcular el rango usando determinantes.

A este número se le conoce simplemente como rango de A (matriz A), y se denota por rang (A).

##Calcular rango de una matriz por determinantes
 

En general, como el rango es el orden de la mayor submatriz cuadrada no nula, los pasos a seguir para el cálculo del rango por determinantes son:

 1  Descartamos las filas (o columnas) que cumplan con alguna de las condiciones:

 

Todos sus coeficientes son ceros.

Hay dos filas (o columnas) iguales.

Una fila (o columna) es proporcional a otra.

Una fila (o columna) es combinación lineal de otras.

 

 2  Si al menos un elemento de la matriz no es cero su determinante no será nulo y, por tanto, el rango será mayor o igual a 1.

 

 3  El rango será mayor o igual a 2 si existe alguna submatriz cuadrada de orden 2, tal que su determinante no sea nulo.

 

 4  El rango será mayor o igual a 3 si existe alguna submatriz cuadrada de orden 3, tal que su determinante no sea nulo.

 

 5 El rango será mayor o igual a 4 si existe alguna submatriz cuadrada de orden

4, tal que su determinante no sea nulo.

 

De este mismo modo se trabaja para comprobar si tiene rango superior a 4, hasta que la submatriz (o las submatrices) del mayor orden posible tenga (o tengan) determinante nulo.

##Aplicación de determinantes para cálculo de la matriz inversa

Definición de inversa de una matriz
 

Se dice que una matriz cuadrada  A  es invertible si existe una matriz  B  con la propiedad de que

   $$ A B = B A = I $$ 

donde  I  es la matriz identidad . La matriz  B  es única, la llamamos la inversa de  A  y la denotamos por  A^{-1}.  Esto es,

   $$ A A^{-1} =A^{-1} A = I. $$ 

 

Observación importante: Una matriz es invertible si y sólo si su determinante es distinto de cero. Esto es, una matriz tiene inversa si su determinante es no cero.

# Independencia Lineal 

## Definición
Sea $S = \{\textbf{v}_1, \textbf{v}_2, ...., \textbf{v}_n \}$ un conjunto no vacío de vectores. 

a) Suponga que:

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

implica que $ \alpha_1 = \alpha_2 = ....=\alpha_n$. Se dice entonces que $\textbf{S}$ es ***linealmente independiente***

b) Un conjunto que no es linealmente independiente se llama ***linealmente dependiente***; análogamente,  $\textbf{S}$ es linealmente dependiente si y solo si hay escalares $ \alpha_1 = \alpha_2 = ....=\alpha_n$ **NO** todos cero, tales que

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

## Python Code
```python 
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)
```


In [ ]:
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)



Coefficients: [ 0.  0. -0.]


## Ejercicios